#!/bin/bash

if [ "$2" == "" ];then
    echo "Usage: $0 <ip file> <outfile>"
    exit 1
fi

if [ ! -f GeoIP.dat ];then
    echo "Can't find GeoIP.dat. Exiting."
    exit 2
fi

if [ -f $2 ];then
    echo "File $2 already exists. Exiting."
    exit 3
fi

which geoiplookup >& /dev/null
if [ $? != 0 ];then
    echo "geoiplookup required."
    exit 4
fi

tempfile=/var/tmp/tempgeofile
tempfile2=/var/tmp/tempgeofile_uniq

echo "Looking up places"
for ip in `cat $1`
do
    geoiplookup -f GeoIP.dat $ip >> $tempfile
done

sort -u $tempfile -o $tempfile2

exec 3<&0
exec 0<$tempfile2
while read line
do
    echo "Processing place: $line"
    echo `grep "$line" $tempfile | wc -l` " : " $line >> $2
done

rm -rf $tempfile
rm -rf $tempfile2

