#!/bin/bash

if [ "$2" == "" ];then
    echo "Usage: $0 <ip file> <outfile>"
    exit 1
fi

if [ ! -f GeoIP.dat ];then
    echo "Can't find GeoIP.dat. Exiting."
    exit 2
fi

if [ -f $2 ];then
    echo "File $2 already exists. Exiting."
    exit 3
fi

tempfile=/var/tmp/tempgeofile

for ip in `cat $1`
do
    geoiplookup -f GeoIP.dat $ip >> $tempfile
done

exec 3<&0
exec 0<$tempfile
while read line
do
    echo "processo $line"
    echo "$line: " `grep "$line" $tempfile | wc -l` >> $2
done

sort -u $2 -o $2
rm -rf $tempfile
