#!/bin/bash

if [ "$2" == "" ];then
    echo "Usage: $0 <ip file> <kml file>"
    exit 1
fi

if [ ! -f GeoLiteCity.dat ];then
    echo "Can't find GeoLiteCity.dat. Exiting."
    exit 2
fi

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<kml xmlns=\"http://www.opengis.net/kml/2.2\">
<Document>
<name>DNS Open relay servers</name>
<description>Locations of DNS open relay servers based on GeoIP database</description>" > $2

for ip in `cat $1`
do
    LOC=`geoiplookup -f GeoLiteCity.dat $ip | awk ' BEGIN { FS="," } { print $7 "," $6 } '`
    #echo "Processing $ip -> $LOC"
    record="<Placemark><name></name><Point><coordinates>$LOC,0</coordinates></Point></Placemark>"
    grep "$record" $2 >& /dev/null
    if [ $? != 0 ];then
    	echo "$record" >> $2
    fi
done

echo "</Document>
</kml>" >> $2

KMZ=`echo $2 | sed 's/kml/kmz/g'`
zip $KMZ $2 &> /dev/null
echo "Output written to $2 and $KMZ"
