#!/bin/bash

if [ "$2" == "" ];then
    echo "Usage: $0 <ip from> <ip to>"
    exit 1
fi

if [ `id -u` != 0 ];then
    echo "Root privileges required"
    exit 2
fi

#DEV=`tty`
DEV=/dev/null

DELAY=5
OUTFILE=results_$1_$2.txt
NETDEV=eth1

if [ -f $OUTFILE ];then
    echo "Output file $OUTFILE exists. Exiting."
    exit 2
fi

slower() {
    for (( i = 0 ; i < $1; i++ )) do
        sleep 1
        echo -n "."
    done
    echo " "
}

echo -n "Starting radar on $NETDEV"
tcpdump -l -nn -i $NETDEV -w radar_$1_$2.pcap udp src port 53 >& $DEV &
RADAR_PID=$!
slower 5
echo "Radar started with pid $RADAR_PID"

echo "Starting scanner"
./scan_dns $1 $2 1000
echo "Scanner finished"

echo "Waiting slow scan packets"
slower 30
echo -n "Stopping radar"
kill -15 $RADAR_PID
slower 5

echo "Parsing results"
tshark -r radar_$1_$2.pcap -l -nn 2> $DEV | awk ' { print $3 } ' | sort -u > $OUTFILE
rm -rf radar.pcap

echo "Output is in file $OUTFILE"
