package filescrambler;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Feb 26, 2010, 1:30:16 PM
 */

/**
 *
 * @author dario
 */
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class MainWindow extends javax.swing.JFrame {

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        statusText.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inTextField = new javax.swing.JTextField();
        inLoadButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        outTextField = new javax.swing.JTextField();
        outLoadButton = new javax.swing.JButton();
        scrambleButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        statusText = new javax.swing.JTextField();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        aboutEntry = new javax.swing.JMenuItem();
        quitEntry = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inLoadButton.setText("Load");
        inLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inLoadButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Input file");

        jLabel2.setText("Output file");

        outLoadButton.setText("Load");
        outLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outLoadButtonActionPerformed(evt);
            }
        });

        scrambleButton.setText("Scramble");
        scrambleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrambleButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        aboutEntry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutEntry.setText("About");
        aboutEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutEntryActionPerformed(evt);
            }
        });
        fileMenu.add(aboutEntry);

        quitEntry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quitEntry.setText("Quit");
        quitEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitEntryActionPerformed(evt);
            }
        });
        fileMenu.add(quitEntry);

        mainMenu.add(fileMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(outTextField)
                            .addComponent(inTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outLoadButton)
                            .addComponent(inLoadButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(scrambleButton)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(statusText, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(inLoadButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(outLoadButton))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scrambleButton)
                    .addComponent(closeButton))
                .addGap(18, 18, 18)
                .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inLoadButtonActionPerformed
        JFileChooser chooser = new JFileChooser();

        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(this, "Invalid File.");
            return;
        }

        inTextField.setText(chooser.getSelectedFile().getAbsolutePath());
}//GEN-LAST:event_inLoadButtonActionPerformed

    private void outLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outLoadButtonActionPerformed
        JFileChooser chooser = new JFileChooser();

        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(this, "Invalid File.");
            return;
        }
        
        outTextField.setText(chooser.getSelectedFile().getAbsolutePath());
}//GEN-LAST:event_outLoadButtonActionPerformed

    private void scrambleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrambleButtonActionPerformed
        try {
            if (inTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Input file must be specified.");
                return;
            }

            if (outTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Output file must be specified.");
                return;
            }

            infile = new FileInputStream(new File(inTextField.getText()));
            outfile = new FileOutputStream(new File(outTextField.getText()));

            int c;
            statusText.setText("Scrambling data.");
            invalidate();
            validate();
            while((c = infile.read()) != -1) {
                outfile.write(~c);
            }
            statusText.setText("");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.toString());
            return;
        }

        statusText.setText("Scrambling done.");
}//GEN-LAST:event_scrambleButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
}//GEN-LAST:event_closeButtonActionPerformed

    private void aboutEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutEntryActionPerformed
        statusText.setText("Code by Dario Lombardo");
    }//GEN-LAST:event_aboutEntryActionPerformed

    private void quitEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitEntryActionPerformed
       System.exit(0);
    }//GEN-LAST:event_quitEntryActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Private vars
    private FileInputStream infile;
    private FileOutputStream outfile;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutEntry;
    private javax.swing.JButton closeButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton inLoadButton;
    private javax.swing.JTextField inTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JButton outLoadButton;
    private javax.swing.JTextField outTextField;
    private javax.swing.JMenuItem quitEntry;
    private javax.swing.JButton scrambleButton;
    private javax.swing.JTextField statusText;
    // End of variables declaration//GEN-END:variables

}
